# Generated by Django 5.0.1 on 2024-01-31 07:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_experience_category_alter_perk_details_and_more'),
        ('reviews', '0001_initial'),
        ('rooms', '0005_room_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewModel',
            new_name='Review',
        ),
    ]
